# Generated by Django 5.2 on 2025-07-21 06:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_payment_mode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='unknown', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_berth',
            field=models.CharField(choices=[('lower', 'Lower'), ('middle', 'Middle'), ('upper', 'Upper'), ('side_lower', 'Side Lower'), ('side_upper', 'Side Upper'), ('any', 'Any')], default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=60)),
                ('journey_date', models.DateField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField()),
                ('passenger_sex', models.CharField(max_length=10)),
                ('preferred_berth', models.CharField(choices=[('lower', 'Lower'), ('middle', 'Middle'), ('upper', 'Upper'), ('side_lower', 'Side Lower'), ('side_upper', 'Side Upper'), ('any', 'Any')], default='any', max_length=16)),
                ('fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('paid_via_wallet', models.BooleanField(default=False)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('payment_pending', 'Payment Pending'), ('booked', 'Booked'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=16)),
                ('pnr', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.booking'),
        ),
        migrations.DeleteModel(
            name='TatkalBooking',
        ),
    ]
